"""Prepositions, time phrases, and pronoun subjects."""

PREPOSITIONS = [
    "in", "on", "at", "by", "to", "for", "from", "with", "near", "past",
    "through", "across", "around", "along", "above", "below", "under",
    "beside", "behind", "beyond", "between", "toward", "against", "among",
    "beneath", "inside", "outside", "within", "without", "before", "after",
    "over", "into", "onto", "upon", "off", "down", "up", "throughout",
    "amid", "alongside", "atop", "opposite", "unlike", "during", "except",
    "since", "until", "via", "worth",
]

TIME_PHRASES = [
    "that morning", "that evening", "that night", "that afternoon",
    "last summer", "last winter", "last spring", "every morning",
    "every evening", "every winter", "for many years", "for a long time",
    "at dawn", "at dusk", "at midnight", "at noon", "on that day",
    "in those days", "long ago", "years later", "the next morning",
    "the following day", "one quiet evening", "on a cold night",
    "during the storm", "before sunrise", "after sunset", "by then",
    "at that moment", "without warning", "all at once", "once again",
    "that autumn", "last autumn", "every afternoon", "for several days",
    "at first light", "in the distance", "the night before", "one summer day",
    "on a clear morning", "after the rain", "before nightfall", "at twilight",
    "the week before", "many months later", "in early spring",
    "late that night", "on the final day", "from that day on",
    "just before noon", "shortly after dawn", "in the dead of night",
    "on a foggy morning", "during the harvest", "throughout the winter",
    "over the weekend", "by the next morning", "toward the end of summer",
    "in the early hours", "at the break of day", "on a rainy afternoon",
    "through the long night", "before the first frost", "after many weeks",
    "sometime that spring", "well past midnight", "in the waning light",
    "as the sun rose", "when the tide turned", "until the very end",
    "for weeks on end", "in the years that followed", "on a still night",
    "just past sunset", "through the autumn months", "before the harvest",
    "near the end of winter", "at the turn of the season", "by late afternoon",
    "on a bright morning", "in the middle of the night", "after the thaw",
    "during those quiet months", "since the beginning of spring",
    "in the fading light", "under the noon sun", "by early evening",
    "the morning after", "on a windswept day", "before the rains came",
    "in the thick of summer", "throughout the long autumn", "at first frost",
    "by the following week", "on the shortest day", "in the months ahead",
    "at the height of summer", "during the coldest week", "long before dawn",
    "on the eve of winter", "through the driest season", "after the long silence",
    "toward the end of autumn", "in the warmth of spring", "on a moonless night",
    "by the time night fell", "just as morning broke", "at the edge of evening",
    "in the pale dawn", "on the longest night", "before the leaves fell",
    "during the last days of summer", "at the close of day", "some weeks later",
    "after the first snow", "in the blaze of noon", "through the bitter cold",
    "on a sweltering afternoon", "well into the evening", "at the start of autumn",
    "by the end of the month", "in the quiet hours", "before the storm broke",
    "on that particular morning", "throughout the short days", "since early autumn",
    "in the hush of evening", "until the stars appeared", "for a brief moment",
    "at the peak of midday", "long after midnight", "on the first warm day",
    "through the wet spring", "near the end of the day", "in the cool of dawn",
    "before the sun climbed high", "after weeks of silence", "during those early days",
    "by the riverside at dusk", "on a gray winter morning", "through the haze of summer",
    "in the gathering dark", "at the stroke of noon", "sometime before dawn",
    "as autumn settled in", "when the snow melted", "in the last light of day",
    "on the far side of midnight", "through the endless afternoon", "toward the first light",
    "by the time spring arrived", "in the stillness of night", "after the dust settled",
    "during the mildest winter", "on the brink of evening", "long past sundown",
    "at the foot of autumn", "in those final hours", "before the world woke",
    "on the clearest night", "through the heart of winter", "near the solstice",
    "since the days grew short", "when the wind shifted", "in the bloom of spring",
    "at the edge of dawn", "well before the frost", "on a hushed afternoon",
    "through those restless nights", "in the shadow of evening",
    "by the last day of the month", "at the turning of the year",
    "on the morning of the storm", "during the spring thaw",
    "after the longest winter", "before the crops ripened",
    "in the calm before dawn", "throughout the dry season",
    "on a day like any other", "in the weeks that followed",
    "by the time the leaves changed", "at the very start of summer",
    "during the shortest days", "near the close of autumn",
    "late in the afternoon", "on a crisp autumn morning",
    "in the hours before midnight", "sometime after the equinox",
    "as the season turned", "when evening finally came",
    "through the fog of early morning", "at the height of the storm",
]

PRONOUNS = [
    "someone", "everyone", "no one", "the stranger", "the traveler",
    "the farmer", "the merchant", "the soldier", "the painter", "the scholar",
    "the teacher", "the hunter", "the sailor", "the doctor", "the builder",
    "the driver", "the author", "the captain", "the prisoner", "the guardian",
    "the servant", "the detective", "the professor", "the inventor",
    "the musician", "the inspector", "the commander", "the pioneer",
    "the villager", "the shepherd", "the apprentice", "the blacksmith",
    "the librarian", "the gardener", "the carpenter", "the fisherman",
    "the innkeeper", "the watchman", "the messenger", "the healer",
]
